# Generated by Django 4.2.4 on 2023-08-30 20:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
