# Generated by Django 4.2.4 on 2023-08-30 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_product_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='product_description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='product_name',
        ),
    ]
